### PR TITLE
Fix license for cat.jpg

### PR DESCRIPTION
**Pull request by silverhook**
The license for `cat.jpg` is CC0-1.0, according to:
<https://cc0.photo/2017/04/11/portrait-orange-cat/>

### CODE REVIEW

**Comment by carmenbianca** [comment]
We deliberately picked a CC0 photo so that we can "lie" about the licence inside of the tutorial, reserving CC0 for configuration files and the like. Perhaps it'd be easier to find a proper CC image instead?

**Comment by silverhook** [comment]
I suspected that could be an explanation for it.

In that case, I retract my pull request, but suggest we write that somewhere in the FAQ or README as a side-note. Not that we *need* to, but it would be good form regardless.

**Comment by mxmehl** [comment]
How about I make a picture from a cat and a dog and license it accordingly so we can use it here "thruthfully"?

**Comment by codebude** [comment]
Hi, I'm the owner of https://cc0.photo Just use the cat picture for whatever you need. When I created the website, I wanted to share pictures for free without the need of any licensing, annotation, ...

**Comment by silverhook** [comment]
> Hi, I'm the owner of https://cc0.photo Just use the cat picture for whatever you need. When I created the website, I wanted to share pictures for free without the need of any licensing, annotation, ...

Hi @codebude, that was well understood on our side, but thank you for confirming :+1: 

The thing still is that (unless we modified the photo) we cannot claim that it is our copyright/authorship – that would still be a plagiarism. Since we’re trying to set up best practices, that’s not the best way.

One option would be to simply keep it as it is, and just clarify in the README or FAQ that the two photos are in fact someone else’s copyright, but we have permission to label them as such just as an example. (But that would still mean the example repo does not include correct info.)

**Pull request closed without merging**
